# Aggregating and Summarizing DataFrames

## Reading and Loading Data

In [1]:
# import the pandas library
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

print(pd.__version__)

2.1.1

In [2]:
# read the big mart sales data
data = pd.read_csv('datasets/big_mart_sales.csv')

# view the top rows of the data
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052


### How to calculate sum, mean, median and mode of a column?

In [3]:
# calculate the metrics of Item_MRP
print('Sum:', data['Item_MRP'].sum())
print('Median:', data['Item_MRP'].median())
print('Mode:', data['Item_MRP'].mode())

Sum: 1201681.4808
Median: 143.0128
Mode: 0    172.0422
Name: Item_MRP, dtype: float64

In [4]:
# Value counts
data['Outlet_Type'].value_counts()

Outlet_Type
Supermarket Type1    5577
Grocery Store        1083
Supermarket Type3     935
Supermarket Type2     928
Name: count, dtype: int64

### How to get the summary of the numerical variables?

In [9]:
# get the summary
data.describe()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,7060.000000,8523.000000,8523.000000,8523.000000,8523.000000
mean,12.857645,0.066132,140.992782,1997.831867,2181.288914
std,4.643456,0.051598,62.275067,8.371760,1706.499616
min,4.555000,0.000000,31.290000,1985.000000,33.290000
25%,8.773750,0.026989,93.826500,1987.000000,834.247400
50%,12.600000,0.053931,143.012800,1999.000000,1794.331000
75%,16.850000,0.094585,185.643700,2004.000000,3101.296400
max,21.350000,0.328391,266.888400,2009.000000,13086.964800

### How to get number of missing values in each columns?

In [5]:
# Checking for NULL values
data.isna().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

### How to group the data based on categories of one column?

#### 'Groupby' function

In [20]:
item_data = data.groupby(['Item_Type'])
item_data

In [21]:
item_data.first()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
Item_Type,,,,,,,,,,,
Baking Goods,FDP36,10.395,Regular,0.000000,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
Breads,FDO23,17.850,Low Fat,0.000000,93.1436,OUT045,2002,Medium,Tier 2,Supermarket Type1,2174.5028
Breakfast,FDP49,9.000,Regular,0.069089,56.3614,OUT046,1997,Small,Tier 1,Supermarket Type1,1547.3192
Canned,FDC14,21.350,Regular,0.072222,43.6454,OUT019,1985,Small,Tier 1,Grocery Store,125.8362
Dairy,FDA15,9.300,Low Fat,0.016047,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
Frozen Foods,FDH17,16.200,Regular,0.016687,96.9726,OUT045,2002,Small,Tier 2,Supermarket Type1,1076.5986
Fruits and Vegetables,FDX07,19.200,Regular,0.000000,182.0950,OUT010,1998,Medium,Tier 3,Grocery Store,732.3800
Hard Drinks,DRI11,11.650,Low Fat,0.034238,113.2834,OUT027,1985,Medium,Tier 3,Supermarket Type3,2303.6680
Health and Hygiene,NCB42,11.800,Low Fat,0.008596,115.3492,OUT018,2009,Medium,Tier 3,Supermarket Type2,1621.8888
Household,NCD19,8.930,Low Fat,0.000000,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
Meat,FDN15,17.500,Low Fat,0.016760,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
Others,NCN07,18.500,Low Fat,0.056816,132.1284,OUT010,1998,Small,Tier 3,Grocery Store,263.6568
Seafood,FDG33,10.395,Regular,0.139561,170.4764,OUT027,1985,Medium,Tier 3,Supermarket Type3,3435.5280
Snack Foods,FDO10,13.650,Regular,0.012741,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
Soft Drinks,DRC01,5.920,Regular,0.019278,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
Starchy Foods,FDH35,18.250,Low Fat,0.000000,164.7526,OUT045,2002,Medium,Tier 2,Supermarket Type1,4604.6728

#### Groupby Mean

In [22]:
# Doing the groupby mean
item_data.mean(numeric_only = True)['Item_MRP']

Item_Type
Baking Goods             126.380766
Breads                   140.952669
Breakfast                141.788151
Canned                   139.763832
Dairy                    148.499208
Frozen Foods             138.503366
Fruits and Vegetables    144.581235
Hard Drinks              137.077928
Health and Hygiene       130.818921
Household                149.424753
Meat                     139.882032
Others                   132.851430
Seafood                  141.841719
Snack Foods              146.194934
Soft Drinks              131.492506
Starchy Foods            147.838023
Name: Item_MRP, dtype: float64

#### Groupby MAX

In [23]:
# Groupby MAX function
item_data.max(numeric_only=True)

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
Item_Type,,,,,
Baking Goods,20.85,0.311090,265.5568,2009,7931.6754
Breads,20.85,0.281510,263.6594,2009,8958.3390
Breakfast,21.10,0.274592,234.9300,2009,8209.3140
Canned,21.35,0.328391,266.8884,2009,10306.5840
Dairy,20.70,0.304737,266.6884,2009,10256.6490
Frozen Foods,20.85,0.294939,264.8910,2009,9678.0688
Fruits and Vegetables,21.35,0.321115,264.2252,2009,12117.5600
Hard Drinks,19.70,0.298205,261.4278,2009,7843.1240
Health and Hygiene,21.25,0.255348,266.6884,2009,9779.9362
Household,21.25,0.325781,264.7910,2009,13086.9648
Meat,21.25,0.287017,261.5936,2009,9390.4432
Others,20.50,0.210596,254.9040,2009,6008.8450
Seafood,20.75,0.256152,240.2880,2009,6503.5344
Snack Foods,21.25,0.303743,264.9568,2009,10993.6896
Soft Drinks,20.75,0.306543,263.5910,2009,9554.2300
Starchy Foods,21.20,0.238366,263.0252,2009,8132.0812

#### How to group the data based on categories of multiple columns?

Calculate the **`average MRP`** of each **`Item_Type`** for each category of **`Outlet_Size`**.

In [27]:
# step wise groupby
data2 = data.groupby(['Outlet_Size', 'Item_Type']).mean(numeric_only=True)
data2['Item_MRP']

Outlet_Size  Item_Type
High         Baking Goods             129.202044
             Breads                   133.758960
             Breakfast                147.490585
             Canned                   135.442708
             Dairy                    153.509173
             Frozen Foods             136.829250
             Fruits and Vegetables    145.572870
             Hard Drinks              141.927522
             Health and Hygiene       135.110980
             Household                147.097522
             Meat                     137.244790
             Others                   132.576613
             Seafood                  134.864240
             Snack Foods              145.847086
             Soft Drinks              131.758473
             Starchy Foods            158.157074
Medium       Baking Goods             126.178568
             Breads                   140.861039
             Breakfast                134.537511
             Canned                   138.124851
             Dairy                    148.512174
             Frozen Foods             140.557015
             Fruits and Vegetables    142.971470
             Hard Drinks              142.837696
             Health and Hygiene       128.701865
             Household                147.711330
             Meat                     136.419132
             Others                   127.836181
             Seafood                  140.857619
             Snack Foods              148.779195
             Soft Drinks              128.269682
             Starchy Foods            148.419504
Small        Baking Goods             125.213364
             Breads                   145.523651
             Breakfast                130.568027
             Canned                   142.295429
             Dairy                    145.942101
             Frozen Foods             137.838544
             Fruits and Vegetables    148.313370
             Hard Drinks              129.758784
             Health and Hygiene       131.831535
             Household                153.965439
             Meat                     145.699250
             Others                   137.889211
             Seafood                  144.281760
             Snack Foods              144.351896
             Soft Drinks              132.855043
             Starchy Foods            150.270174
Name: Item_MRP, dtype: float64

### Using Pivot Table

Calculate the **`average MRP`** of each **`Item_Type`** using pivot table.

In [28]:
# Pivot table
pd.pivot_table(data, index = 'Item_Type', values = 'Item_MRP', aggfunc = 'mean')

                         Item_MRP
Item_Type
Baking Goods           126.380766
Breads                 140.952669
Breakfast              141.788151
Canned                 139.763832
Dairy                  148.499208
Frozen Foods           138.503366
Fruits and Vegetables  144.581235
Hard Drinks            137.077928
Health and Hygiene     130.818921
Household              149.424753
Meat                   139.882032
Others                 132.851430
Seafood                141.841719
Snack Foods            146.194934
Soft Drinks            131.492506
Starchy Foods          147.838023

Calculate the **`average MRP`** of each **`Item_Type`** for each category of **`Outlet_Size`** using pivot table.

In [29]:
# Pivot table
pd.pivot_table(data, index= ['Outlet_Size', 'Item_Type'], values= 'Item_MRP', aggfunc= 'mean')

                                     Item_MRP
Outlet_Size Item_Type
High        Baking Goods           129.202044
            Breads                 133.758960
            Breakfast              147.490585
            Canned                 135.442708
            Dairy                  153.509173
            Frozen Foods           136.829250
            Fruits and Vegetables  145.572870
            Hard Drinks            141.927522
            Health and Hygiene     135.110980
            Household              147.097522
            Meat                   137.244790
            Others                 132.576613
            Seafood                134.864240
            Snack Foods            145.847086
            Soft Drinks            131.758473
            Starchy Foods          158.157074
Medium      Baking Goods           126.178568
            Breads                 140.861039
            Breakfast              134.537511
            Canned                 138.124851
            Dairy                  148.512174
            Frozen Foods           140.557015
            Fruits and Vegetables  142.971470
            Hard Drinks            142.837696
            Health and Hygiene     128.701865
            Household              147.711330
            Meat                   136.419132
            Others                 127.836181
            Seafood                140.857619
            Snack Foods            148.779195
            Soft Drinks            128.269682
            Starchy Foods          148.419504
Small       Baking Goods           125.213364
            Breads                 145.523651
            Breakfast              130.568027
            Canned                 142.295429
            Dairy                  145.942101
            Frozen Foods           137.838544
            Fruits and Vegetables  148.313370
            Hard Drinks            129.758784
            Health and Hygiene     131.831535
            Household              153.965439
            Meat                   145.699250
            Others                 137.889211
            Seafood                144.281760
            Snack Foods            144.351896
            Soft Drinks            132.855043
            Starchy Foods          150.270174

### Cross Tab Function

- The **crosstab()** function is used to compute a frequency table of two or more factors. 
- By default, it computes a frequency table of the factors unless an array of values or an aggregation function which is passed.

In [30]:
# Creating a cross tab
pd.crosstab(data['Outlet_Size'], data['Item_Type'])

Item_Type,Baking Goods,Breads,Breakfast,Canned,Dairy,Frozen Foods,Fruits and Vegetables,Hard Drinks,Health and Hygiene,Household,Meat,Others,Seafood,Snack Foods,Soft Drinks,Starchy Foods
Outlet_Size,,,,,,,,,,,,,,,,
High,73,25,13,65,80,92,142,23,61,103,41,16,5,125,49,19
Medium,203,83,36,217,218,274,413,75,170,289,149,52,21,408,137,48
Small,187,71,30,189,198,249,328,50,136,257,119,55,20,335,126,38

### How to create new feature using the aggregated results of a column?

####  Using the transform function.

The time taken by the transform function to perform the operation is comparatively less over a large dataframe. That’s a sigificant advantage as comapred to the first approach we used.

In [32]:
data['average_item_visibility'] = data.groupby(['Item_Identifier'])['Item_Visibility'].transform('mean')
data[['average_item_visibility']].head()

   average_item_visibility
0                 0.017387
1                 0.019219
2                 0.020145
3                 0.015274
4                 0.008082